export const HEADER_TEXT = {
  openSearch: "Open search",
  closeSearch: "Close search",
  submitSearch: "Submit search",
  searchLabel: "Search",
  searchPlaceholder: "Search",
  openMenu: "Open menu",
  closeMenu: "Close menu",
  calendarIconAlt: "Calendar",
  checkInLabel: "Check In",
  checkOutLabel: "Check Out",
  selectADate: "Select a date",
  roomsLabel: "Rooms",
  guestsPerRoomLabel: "Guests Per Room",
  promoCodeLabel: "Promo Code",
  checkAvailability: "Check Availability",
  decreaseRooms: "Decrease rooms",
  increaseRooms: "Increase rooms",
  decreaseGuestsPerRoom: "Decrease guests per room",
  increaseGuestsPerRoom: "Increase guests per room",
  decreaseIconAlt: "Decrease",
  increaseIconAlt: "Increase",
} as const;
